# Generated by Django 4.2.7 on 2026-07-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
